# Generated by Django 4.1.7 on 2023-02-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Doctor', 'Doctor'), ('Tattoo Studio', 'Tattoo Studio'), ('Nurse', 'Nurse'), ('Care-Facility', 'Care-Facility')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=12)),
                ('document', models.FileField(upload_to='uploads')),
            ],
        ),
    ]
