# Generated by Django 4.1.7 on 2023-02-23 12:00

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='document',
        ),
        migrations.AddField(
            model_name='patients',
            name='identity_doc',
            field=models.FileField(null=True, upload_to='uploaded_files', validators=[main.models.patients.validate_file_extension]),
        ),
        migrations.AddField(
            model_name='patients',
            name='residency',
            field=models.FileField(null=True, upload_to='uploaded_files', validators=[main.models.patients.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.patients'),
        ),
    ]
