# Generated by Django 4.1.7 on 2023-02-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice_name', models.CharField(max_length=100)),
                ('practice_number', models.BigIntegerField(max_length=250)),
                ('doc_name', models.CharField(max_length=255)),
                ('practice_phone_number', models.CharField(max_length=100)),
                ('address_details', models.TextField()),
                ('banking_details', models.TextField()),
                ('practice_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
