# Generated by Django 4.1.7 on 2023-02-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='practice_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='practice_number',
            field=models.CharField(max_length=250),
        ),
    ]
